all:
	g++ Pi_0.cpp -fopenmp -o Pi_0
	g++ Pi_1.cpp -fopenmp -o Pi_1
	g++ Pi_2.cpp -fopenmp -o Pi_2
	g++ Pi_3.cpp -fopenmp -o Pi_3
	g++ Pi_4.cpp -fopenmp -o Pi_4
	g++ PSRS.cpp -fopenmp -o PSRS

clean: 
	rm -rf Pi_0 Pi_1 Pi_2 Pi_3 Pi_4 PSRS
